export default {
  x: 0,
  y: 0,
  "line-width": 2,
  "line-length": 40,
  "text-margin": 8,
  "font-size": 14,
  "font-color": "#8DA1AC",
  "line-color": "#8DA1AC",
  "element-color": "black",
  fill: "white",
  "yes-text": "Yes",
  "no-text": "No",
  "arrow-end": "block",
  scale: 1,
};
