# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Mister_Hope
open_collective: vuepress-theme-hope
custom:
  - https://mister-hope.com/about/donate.html
