# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: theMisterHope
open_collective: vuepress-theme-hope
custom:
  - https://qr.alipay.com/a7x02363sw6mccgvlpbitc5
