root: true

env:
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:vue/recommended
  - prettier
  - prettier/vue
  - "@vue/typescript"

plugins:
  - prettier
  - vue

rules:
  comma-dangle:
    - off

  complexity:
    - warn
    - max: 25

  curly:
    - error
    - multi

  id-length:
    - error
    - min: 2
      exceptions:
        - a
        - b
        - h
        - i
        - j
        - k

  indent:
    - off

  max-statements:
    - warn
    - 25

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-warning-comments:
    - warn

  object-curly-spacing:
    - off

  prefer-destructuring:
    - error
    - object: true
      array: false

  quotes:
    - off

  radix:
    - error
    - as-needed

  vue/require-default-prop:
    - warn

  vue/html-self-closing:
    - error
    - html:
        void: always

  vue/max-attributes-per-line:
    - error
    - singleline: 5

  vue/no-v-html:
    - off

overrides:
  - files:
      - "index.js"

    rules:
      camelcase:
        - off

  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier/@typescript-eslint

    plugins:
      - "@typescript-eslint"

    parser: "vue-eslint-parser"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"
        - "./commonjs-tsconfig.json"
        - "./test-tsconfig.json"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - warn

  - files:
      - "*.d.ts"
    rules:
      no-underscore-dangle:
        - off

  - files:
      - "*.vue"

    rules:
      no-unused-vars:
        - off

  - files:
      - "**/test/**/*.spec.js"
      - "**/test/**/*.spec.ts"
      - "**/test/**/*.test.js"
      - "**/test/**/*.test.ts"

    env:
      mocha: true

    rules:
      id-length: "off"
      max-lines-per-function: "off"

  - files:
      - "**/test/**/*.spec.ts"
      - "**/test/**/*.test.ts"

    rules:
      "@typescript-eslint/no-explicit-any":
        - off

      "@typescript-eslint/no-unsafe-member-access":
        - off
