extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /inset/
  media-feature-range-notation: prefix
  no-descending-specificity: null
