extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties: true
  media-feature-range-notation: prefix
  no-descending-specificity: null
ignoreFiles:
  - "**/*.module.scss"
