extends:
  - stylelint-config-hope
rules:
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /inset/
        - margin-block
        # Android wechat browser support
        - margin-inline
        # Android wechat browser support
        - padding-inline
        - place-content
  media-feature-range-notation: prefix
  no-descending-specificity: null
