packages:
  - demo/*
  - docs/*
  - docs-shared/
  - packages/*

catalog:
  "@mathjax/src": 4.1.0
  "@vueuse/core": 14.1.0
  markmap-lib: 0.18.12
  markmap-toolbar: 0.18.12
  markmap-view: 0.18.12
  mermaid: 11.12.2
  reveal.js: 5.2.1
  sass-embedded: 1.97.1
  sass-loader: 16.0.6
  vue: 3.5.26

catalogs:
  range:
    "@vueuse/core": ^14.1.0
    balloon-css: ^1.2.0
    sass: ^1.97.1
    sass-embedded: ^1.97.1
    sass-loader: ^16.0.6
    vue: ^3.5.26
  vuepress:
    "@vuepress/bundler-vite": 2.0.0-rc.26
    "@vuepress/bundler-webpack": 2.0.0-rc.26
    "@vuepress/helper": 2.0.0-rc.121
    "@vuepress/highlighter-helper": 2.0.0-rc.118
    "@vuepress/plugin-active-header-links": 2.0.0-rc.118
    "@vuepress/plugin-back-to-top": 2.0.0-rc.121
    "@vuepress/plugin-blog": 2.0.0-rc.121
    "@vuepress/plugin-catalog": 2.0.0-rc.121
    "@vuepress/plugin-comment": 2.0.0-rc.121
    "@vuepress/plugin-copy-code": 2.0.0-rc.121
    "@vuepress/plugin-copyright": 2.0.0-rc.121
    "@vuepress/plugin-docsearch": 2.0.0-rc.121
    "@vuepress/plugin-feed": 2.0.0-rc.121
    "@vuepress/plugin-git": 2.0.0-rc.121
    "@vuepress/plugin-icon": 2.0.0-rc.121
    "@vuepress/plugin-links-check": 2.0.0-rc.121
    "@vuepress/plugin-markdown-chart": 2.0.0-rc.121
    "@vuepress/plugin-markdown-ext": 2.0.0-rc.121
    "@vuepress/plugin-markdown-hint": 2.0.0-rc.121
    "@vuepress/plugin-markdown-image": 2.0.0-rc.121
    "@vuepress/plugin-markdown-include": 2.0.0-rc.121
    "@vuepress/plugin-markdown-math": 2.0.0-rc.121
    "@vuepress/plugin-markdown-preview": 2.0.0-rc.121
    "@vuepress/plugin-markdown-stylize": 2.0.0-rc.121
    "@vuepress/plugin-markdown-tab": 2.0.0-rc.121
    "@vuepress/plugin-meilisearch": 2.0.0-rc.121
    "@vuepress/plugin-notice": 2.0.0-rc.121
    "@vuepress/plugin-nprogress": 2.0.0-rc.121
    "@vuepress/plugin-photo-swipe": 2.0.0-rc.121
    "@vuepress/plugin-prismjs": 2.0.0-rc.121
    "@vuepress/plugin-pwa": 2.0.0-rc.121
    "@vuepress/plugin-reading-time": 2.0.0-rc.121
    "@vuepress/plugin-redirect": 2.0.0-rc.121
    "@vuepress/plugin-revealjs": 2.0.0-rc.121
    "@vuepress/plugin-rtl": 2.0.0-rc.121
    "@vuepress/plugin-sass-palette": 2.0.0-rc.121
    "@vuepress/plugin-search": 2.0.0-rc.121
    "@vuepress/plugin-seo": 2.0.0-rc.121
    "@vuepress/plugin-shiki": 2.0.0-rc.121
    "@vuepress/plugin-sitemap": 2.0.0-rc.121
    "@vuepress/plugin-slimsearch": 2.0.0-rc.121
    "@vuepress/plugin-theme-data": 2.0.0-rc.120
    "@vuepress/plugin-watermark": 2.0.0-rc.121
    "@vuepress/shiki-twoslash": 2.0.0-rc.121
    "@vuepress/theme-default": 2.0.0-rc.121
    vuepress: 2.0.0-rc.26

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

overrides:
  esbuild: ^0.27.1
  react: ^19.2.3

patchedDependencies:
  "@rollup/plugin-alias": patches/@rollup__plugin-alias.patch

peerDependencyRules:
  allowedVersions:
    echarts-wordcloud@2>echarts: ^6.0.0
