name: Bug report
description: Create a report to help us improve
title: "[Bug]"
labels:
  - bug
assignees: Mister-Hope
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure that you follow these statements.
      options:
        - label: I am using the **latest version**
          required: true

        - label: I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))
          required: true

  - type: input
    id: package
    attributes:
      label: Package name
      description: Which package are you reporting
      value: vuepress-theme-hope
      placeholder: package name
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of theme or plugins are you using?
      multiple: false
      options:
        - v1
        - v2
    validations:
      required: true

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating system are you using?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > If applicable, add screenshots and log to help explain your problem.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: If you are not reporting something obvious, a minial reproductin repo and related log is required.
      placeholder: Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.
