name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]"
labels:
  - enhancement
assignees: Mister-Hope
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure that you follow these statements.
      options:
        - label: I searched existing issues and no one else requests similar feature.
          required: true

        - label: I think that 25%+ users are positive towards this feature.
          required: true

  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: What's it for and why you want
      placeholder: A clear and concise description of what the feature is, and what it will enhance or solve. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
