const options = {
  allowJs: false,
  allowSyntheticDefaultImports: true,
  allowUnreachableCode: false,
  allowUnusedLabels: false,
  alwaysStrict: false,
  declaration: false,
  diagnostics: false,
  downlevelIteration: false,
  experimentalDecorators: true,
  esModuleInterop: false,
  forceConsistentCasingInFileNames: true,
  importHelpers: false,
  inlineSourceMap: false,
  inlineSources: false,
  listEmittedFiles: true,
  module: 'commonjs',
  moduleResolution: 'node',
  noFallthroughCasesInSwitch: true,
  noImplicitAny: true,
  noImplicitReturns: true,
  noImplicitThis: true,
  noUnusedParameters: true,
  pretty: true,
  removeComments: false,
  sourceMap: false,
  strict: true,
  strictNullChecks: true,
  strictPropertyInitialization: true,
  target: 'es6',
  types: ['vuepress-types']
};

export default options;
