export const PLUGIN_CHECKLIST = [
  ["@vuepress/plugin-active-header-links", "activeHeaderLinks"],
  ["@vuepress/plugin-blog", "blog"],
  ["@vuepress/plugin-catalog", "catalog"],
  ["@vuepress/plugin-comment", "comment"],
  ["@vuepress/plugin-copy-code", "copyCode"],
  ["@vuepress/plugin-copyright", "copyright"],
  ["@vuepress/plugin-docsearch", "docsearch"],
  ["@vuepress/plugin-feed", "feed"],
  ["@vuepress/plugin-git", "git"],
  ["@vuepress/plugin-links-check", "linksCheck"],
  [
    "@vuepress/plugin-markdown-hint",
    "",
    'Set "markdown.alert" and "markdown.hint" in theme options',
  ],
  [
    "@vuepress/plugin-markdown-image",
    "",
    'Set "markdown.figure", "markdown.imgLazyload", "markdown.imgMark", "markdown.imgSize" and "markdown.obsidianImgSize" in theme options',
  ],
  [
    "@vuepress/plugin-markdown-math",
    "",
    'Set "markdown.math" in theme options',
  ],
  [
    "@vuepress/plugin-markdown-tab",
    "",
    "Set 'markdown.tabs' and 'markdown.codeTabs' in theme options",
  ],
  ["@vuepress/plugin-notice", "notice"],
  ["@vuepress/plugin-nprogress", "nprogress"],
  ["@vuepress/plugin-photo-swipe", "photoSwipe"],
  ["@vuepress/plugin-prismjs", "prismjs"],
  ["@vuepress/plugin-pwa", "pwa"],
  ["@vuepress/plugin-reading-time", "readingTime"],
  ["@vuepress/plugin-redirect", "redirect"],
  ["@vuepress/plugin-revealjs", "", 'Set "markdown.revealjs" in theme options'],
  ["@vuepress/plugin-rtl", "", 'Set "rtl: true" in the needed theme locales.'],
  ["@vuepress/plugin-search", "search"],
  ["@vuepress/plugin-seo", "seo"],
  ["@vuepress/plugin-shiki", "shiki"],
  ["@vuepress/plugin-sitemap", "sitemap"],
  ["@vuepress/plugin-theme-data", "", "This plugin is called internally."],
  ["@vuepress/plugin-watermark", "watermark"],
  ["vuepress-plugin-components", "components"],
  ["vuepress-plugin-md-enhance", "mdEnhance"],
  ["vuepress-plugin-search-pro", "searchPro"],
];
