import { colors } from "vuepress/utils";

export const PLUGIN_CHECKLIST = [
  ["@vuepress/plugin-active-header-links", "activeHeaderLinks"],
  ["@vuepress/plugin-blog", "blog"],
  ["@vuepress/plugin-catalog", "catalog"],
  ["@vuepress/plugin-comment", "comment"],
  ["@vuepress/plugin-copy-code", "copyCode"],
  ["@vuepress/plugin-copyright", "copyright"],
  ["@vuepress/plugin-docsearch", "docsearch"],
  ["@vuepress/plugin-feed", "feed"],
  ["@vuepress/plugin-git", "git"],
  ["@vuepress/plugin-icon", "icon"],
  [
    "@vuepress/plugin-links-check",
    "",
    `Set ${colors.cyan("markdown.linksCheck")} in theme options`,
  ],
  [
    "@vuepress/plugin-markdown-hint",
    "",
    `Set ${colors.cyan("markdown.alert")} and${colors.cyan("markdown.hint")} in theme options`,
  ],
  [
    "@vuepress/plugin-markdown-image",
    "",
    `Set ${colors.cyan("markdown.figure")}, ${colors.cyan("markdown.imgLazyload")}, ${colors.cyan("markdown.imgMark")}, ${colors.cyan("markdown.imgSize")} and ${colors.cyan("markdown.obsidianImgSize")} in theme options`,
  ],
  [
    "@vuepress/plugin-markdown-math",
    "",
    `Set ${colors.cyan("markdown.math")} in theme options`,
  ],
  [
    "@vuepress/plugin-markdown-tab",
    "",
    `Set ${colors.cyan("markdown.tabs")} and ${colors.cyan("markdown.codeTabs")} in theme options`,
  ],
  ["@vuepress/plugin-notice", "notice"],
  ["@vuepress/plugin-nprogress", "nprogress"],
  ["@vuepress/plugin-photo-swipe", "photoSwipe"],
  [
    "@vuepress/plugin-prismjs",
    "",
    `Set ${colors.cyan('markdown.highlighter: { type: "prismjs", ... your options }')} in theme options`,
  ],
  ["@vuepress/plugin-pwa", "pwa"],
  ["@vuepress/plugin-reading-time", "readingTime"],
  ["@vuepress/plugin-redirect", "redirect"],
  [
    "@vuepress/plugin-revealjs",
    "",
    `Set ${colors.cyan("markdown.revealjs")} in theme options`,
  ],
  ["@vuepress/plugin-rtl", "", 'Set "rtl: true" in the needed theme locales.'],
  ["@vuepress/plugin-search", "search"],
  ["@vuepress/plugin-seo", "seo"],
  [
    "@vuepress/plugin-shiki",
    "",
    `Set ${colors.cyan('markdown.highlighter: { type: "shiki", ... your options }')} in theme options`,
  ],
  ["@vuepress/plugin-slimsearch", "slimsearch"],
  ["@vuepress/plugin-sitemap", "sitemap"],
  ["@vuepress/plugin-theme-data", "", "This plugin is called internally."],
  ["@vuepress/plugin-watermark", "watermark"],
  ["vuepress-plugin-components", "components"],
  ["vuepress-plugin-md-enhance", "mdEnhance"],
];
