import {
  BaiduIcon,
  BitbucketIcon,
  DingdingIcon,
  DiscordIcon,
  DribbbleIcon,
  EmailIcon,
  EvernoteIcon,
  FacebookIcon,
  FlipboardIcon,
  GiteeIcon,
  GithubIcon,
  GitlabIcon,
  GmailIcon,
  InstagramIcon,
  LinesIcon,
  LinkedinIcon,
  PinterestIcon,
  PocketIcon,
  QQIcon,
  QzoneIcon,
  RedditIcon,
  RssIcon,
  SteamIcon,
  TwitterIcon,
  WechatIcon,
  WeiboIcon,
  WhatsappIcon,
  YoutubeIcon,
  ZhihuIcon,
} from "./icons";

import type { FunctionalComponent } from "vue";
import type { MediaType } from "../../../shared";

export const iconMap: Record<MediaType, FunctionalComponent> = {
  Baidu: BaiduIcon,
  Bitbucket: BitbucketIcon,
  Dingding: DingdingIcon,
  Discord: DiscordIcon,
  Dribbble: DribbbleIcon,
  Email: EmailIcon,
  Evernote: EvernoteIcon,
  Facebook: FacebookIcon,
  Flipboard: FlipboardIcon,
  Gitee: GiteeIcon,
  Github: GithubIcon,
  Gitlab: GitlabIcon,
  Gmail: GmailIcon,
  Instagram: InstagramIcon,
  Lines: LinesIcon,
  Linkedin: LinkedinIcon,
  Pinterest: PinterestIcon,
  Pocket: PocketIcon,
  QQ: QQIcon,
  Qzone: QzoneIcon,
  Reddit: RedditIcon,
  Rss: RssIcon,
  Steam: SteamIcon,
  Twitter: TwitterIcon,
  Wechat: WechatIcon,
  Weibo: WeiboIcon,
  Whatsapp: WhatsappIcon,
  Youtube: YoutubeIcon,
  Zhihu: ZhihuIcon,
};
