import type { HopeThemeSidebarConfig } from "vuepress-theme-hope";

export const enSidebarConfig: HopeThemeSidebarConfig = {
  "/guide/": [
    {
      text: "Get Started",
      icon: "creative",
      prefix: "get-started/",
      collapsable: true,
      children: ["intro", "install", "markdown"],
    },
    {
      text: "Interface",
      icon: "palette",
      prefix: "interface/",
      collapsable: true,
      children: [
        "darkmode",
        "theme-color",
        "icon",
        "code-theme",
        "accessibility",
        "others",
      ],
    },
    {
      text: "Layout",
      icon: "layout",
      prefix: "layout/",
      collapsable: true,
      children: [
        "navbar",
        "sidebar",
        "page",
        "breadcrumb",
        "footer",
        "home",
        "slides",
      ],
    },
    {
      text: "Markdown enhance",
      icon: "markdown",
      prefix: "markdown/",
      collapsable: true,
      children: [
        "intro",
        "container",
        "components",
        "code-group",
        "align",
        "sup-sub",
        "footnote",
        "mark",
        "tasklist",
        "tex",
        "flowchart",
        "mermaid",
        "demo",
        "presentation",
        "external",
      ],
    },
    {
      text: "Features",
      icon: "discover",
      prefix: "feature/",
      collapsable: true,
      children: [
        "page-info",
        "comment",
        "copy-code",
        "photo-swipe",
        "meta",
        "search",
        "encrypt",
      ],
    },
    {
      text: "Blog",
      icon: "blog",
      prefix: "blog/",
      collapsable: true,
      children: ["intro", "article", "category-and-tags", "timeline", "home"],
    },
    {
      text: "Advanced",
      icon: "advance",
      prefix: "advanced/",
      collapsable: true,
      children: ["pwa", "feed", "seo", "sitemap", "customize", "extend"],
    },
  ],

  "/config/": [
    "intro",
    "i18n",
    {
      text: "Theme Config",
      icon: "config",
      prefix: "theme/",
      children: ["", "basic", "feature", "layout", "apperance"],
    },
    {
      text: "Plugin Config",
      icon: "plugin",
      prefix: "plugins/",
      children: [
        "intro",
        "blog",
        "comment",
        "feed",
        "md-enhance",
        "pwa",
        "others",
      ],
    },
    "page",
    "style",
  ],

  "/basic/": [
    "tutorial",
    {
      text: "Markdown",
      icon: "markdown",
      prefix: "markdown/",
      children: [
        "",
        "demo",
        {
          text: "Emoji",
          icon: "emoji",
          link: "emoji/",
          prefix: "emoji/",
          children: ["people", "nature", "object", "place", "symbol"],
        },
      ],
    },
    {
      text: "VuePress",
      icon: "vue",
      prefix: "vuepress/",
      children: ["", "page", "markdown", "file", "config", "plugin", "theme"],
    },
  ],

  "/": [
    "",
    {
      text: "Guide",
      icon: "creative",
      prefix: "guide/",
      children: [
        "get-started/",
        "interface/",
        "layout/",
        "markdown/",
        "feature/",
        "blog/",
        "advanced/",
      ],
    },
    {
      text: "Config",
      icon: "config",
      prefix: "config/",
      children: ["intro", "i18n", "theme/", "plugins/", "page", "style"],
    },
    {
      text: "Basic",
      icon: "module",
      prefix: "basic/",
      children: ["tutorial", "markdown/", "vuepress/"],
    },
    {
      text: "Migration",
      icon: "change",
      prefix: "migration",
      children: ["config", "page", "style"],
    },
    "changelog",
    "faq",
    "demo/",
    "contribution",
  ],
};
