export type AvailableComponent =
  | "ArtPlayer"
  | "AudioPlayer"
  | "Badge"
  | "BiliBili"
  | "CodePen"
  | "FontIcon"
  | "PDF"
  | "Replit"
  | "Share"
  | "StackBlitz"
  | "SiteInfo"
  | "VPBanner"
  | "VPCard"
  | "VidStack"
  | "VideoPlayer"
  | "XiGua"
  | "YouTube";
