name: Publish Packages

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@^24.18.0

      - name: Install deps
        run: pnpm ci

      - name: Build project
        run: pnpm run build

      - name: Publish packages
        run: pnpm publish -r --no-git-checks

      - name: Sync npmmirror
        run: pnpm release:sync
